import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
}

rootProject.ext.mavenUserName=""
rootProject.ext.mavenPassword=""

if (file("./build.gradle.local").exists()) {
    apply from: "./build.gradle.local"
}

allprojects {
    group 'uk.co.notnull'
    version '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
        mavenLocal()

        maven {
            url 'https://repo.not-null.co.uk/snapshots/'
        }
        maven {
            url "https://papermc.io/repo/repository/maven-public/"
        }
    }

    compileJava {
        options.compilerArgs += ["-Xlint:all", "-Xlint:-processing"]
        options.encoding = 'UTF-8'
    }
}

dependencies {
    implementation project(':CustomItemsAPI')

    compileOnly messagesHelperDependency
    compileOnly 'org.jetbrains:annotations:26.0.1'
    compileOnly "io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT"
}

java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21

task processSource(type: Sync) {
    from sourceSets.main.java
    filter(ReplaceTokens, tokens: [('messagesHelperDependency'): messagesHelperDependency])
    into "${layout.buildDirectory.get()}/src"
}

tasks {
    processResources {
        from("${project.rootDir}/src/main/resources") {
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
            project.properties.findAll().each {
                prop ->
                    if (prop.value != null && prop.value instanceof java.lang.String) {
                        filter(ReplaceTokens, tokens: [(prop.key): prop.value])
                        filter(ReplaceTokens, tokens: [('project.' + prop.key): prop.value])
                    }
            }
        }
    }

    compileJava {
        dependsOn(clean)
        source = processSource.outputs
        options.compilerArgs += ["-Xlint:all", "-Xlint:-processing"]
        options.encoding = 'UTF-8'
    }

    // Include API classes in jar
    jar {
        from {
            subprojects.collect { it.sourceSets.main.output }
        }
    }
}
