claimChestLocation:
  world: world
  x: 4
  y: 74
  z: -75
items:
  detailing_participant:
    type: "minecraft:feather"
    components:
      custom_model_data: 1
      item_name: 'Detailing Contest Participant'
      lore:
        - Awarded to <player> for
        - Participating in the Chunk Detailing
        - Contest
  detailing_winner:
    type: "minecraft:feather"
    components:
      custom_model_data: 2
      item_name: 'Detailing Contest Winner'
      lore:
        - Awarded to <player> for
        - submitting a winning entry
        - in the Chunk Detailing Contest
  cano3:
    type: "minecraft:feather"
    stamp: false
    components:
      custom_model_data: 1037
      item_name: 'Cano3'
      lore:
        - By whoever made cano3
      equippable:
        slot: head

loot:
  emotes:
    - cano3