claimChestLocation:
  world: world
  x: 4
  y: 74
  z: -75
items:
  detailing_participant:
    item: FEATHER
    model: 1
    name: 'Detailing Contest Participant'
    lore:
      - Awarded to <player> for
      - Participating in the Chunk Detailing
      - Contest
  detailing_winner:
    item: FEATHER
    model: 2
    name: 'Detailing Contest Winner'
    lore:
      - Awarded to <player> for
      - submitting a winning entry
      - in the Chunk Detailing Contest
  cano3:
    item: FEATHER
    model: 1037
    name: 'Cano3'
    wearable: true
    lore:
      - By whoever made cano3
    stamp: false

loot:
  emotes:
    - cano3