name: CustomItems
version: @project.version@
author: Jim (AnEnragedPigeon)
description: Custom Items
api-version: '1.21'

main: uk.co.notnull.CustomItems.CustomItemsImpl
loader: uk.co.notnull.CustomItems.CustomItemsLoader

permissions:
  customitems.give:
    default: op
    description: Access to /give
  customitems.givepool:
    default: op
    description: Access to /givepool
  customitems.grant:
    default: op
    description: Access to /grant
  customitems.revoke:
    default: op
    description: Access to /revoke
  customitems.reload:
    default: op
    description: Access to /reload
  customitems.view:
    default: op
    description: Access to /viewunclaimed