name: CustomItems
version: @project.version@
author: Jim (AnEnragedPigeon)
description: Custom Items
api-version: '1.21'

main: uk.co.notnull.CustomItems.CustomItemsImpl
loader: uk.co.notnull.CustomItems.CustomItemsLoader
