name: CustomItems
version: @project.version@
author: Jim
description: Custom Items

main: uk.co.notnull.CustomItems.CustomItemsImpl
loader: uk.co.notnull.CustomItems.CustomItemsLoader
api-version: 1.20.6
